/* ============================================
   Museo Virtual AAAJ — Datos
   Esta versión usa datos públicos verificables (Wikipedia, sitio oficial)
   + placeholders donde se llenará con los Excels del archivo histórico.
   Cuando llegue la data real, reemplazar valores acá.
   ============================================ */

const DATA = {
  meta: {
    fundacion: "15 de agosto de 1904",
    estadio: "Diego Armando Maradona",
    barrio: "La Paternal, CABA",
    apodos: ["El Bicho", "Los Bichitos Colorados", "Los Cebollitas"],
    colores: ["#C8102E", "#FFFFFF"],
  },

  // ===== JUGADORES =====
  jugadores: [
    {
      id: "maradona",
      nombre: "Diego Armando Maradona",
      apodo: "El Diez",
      iniciales: "DM",
      posicion: "Mediocampista ofensivo",
      periodo: "1976 — 1981",
      debutFecha: "20 de octubre de 1976",
      debutDetalle: "Talleres (Córdoba) vs Argentinos Juniors",
      partidos: 167,
      goles: 116,
      titulos: ["Cebollitas — campeón juvenil"],
      bio: "Diego debutó en Primera con 15 años, 11 meses y 21 días — el más joven de la historia del club hasta ese momento. Surgido de Los Cebollitas, las inferiores que se hicieron leyenda en los 70, jugó cinco temporadas como bichito antes de partir a Boca. En Argentinos marcó 116 goles en 167 partidos, números que lo dejan entre los máximos goleadores históricos de la institución.",
      cita: {
        texto: "Cuando salí a la cancha por primera vez, sentí que el pasto me hablaba. Argentinos me hizo futbolista.",
        autor: "Diego Maradona",
      },
      partidosDestacados: ["debut-maradona", "final-liberta-85"],
      camisetasUsadas: ["clasica-anos-80"],
    },
    {
      id: "batista",
      nombre: "Sergio Daniel Batista",
      apodo: "El Checho",
      iniciales: "SB",
      posicion: "Mediocampista central",
      periodo: "1981 — 1988",
      debutFecha: "1981",
      debutDetalle: "Surgido de las inferiores del club",
      partidos: null,
      goles: null,
      titulos: [
        "Copa Libertadores 1985",
        "Copa Interamericana 1986",
        "Mundial México 1986 (Selección Argentina)",
      ],
      bio: "Volante central de marca y juego. Pieza clave del equipo de Argentinos campeón de América en 1985 y, un año después, mediocampista titular de la Selección Argentina campeona del mundo en México. Su trabajo silencioso en el medio fue uno de los pilares del ciclo más glorioso del club.",
      cita: {
        texto: "Aquel equipo del 85 fue una familia. Lo que conseguimos no se vuelve a repetir.",
        autor: "Sergio Batista",
      },
      partidosDestacados: ["final-liberta-85", "final-intercontinental-85"],
      camisetasUsadas: ["clasica-anos-80", "edicion-libertadores-85"],
    },
    {
      id: "borghi",
      nombre: "Claudio Daniel Borghi",
      apodo: "El Bichi",
      iniciales: "CB",
      posicion: "Mediocampista ofensivo",
      periodo: "1981 — 1987",
      debutFecha: "1981",
      debutDetalle: "Surgido de las inferiores del club",
      partidos: null,
      goles: null,
      titulos: [
        "Copa Libertadores 1985",
        "Copa Interamericana 1986",
        "Mundial México 1986 (Selección Argentina)",
      ],
      bio: "Enganche talentoso y una de las grandes figuras del Argentinos campeón de América. Tras la consagración en la Libertadores 1985, su nombre dio la vuelta al mundo cuando enfrentó a la Juventus de Platini en la final Intercontinental de Tokio. Mundialista en México 86 con la Selección.",
      cita: null,
      partidosDestacados: ["final-liberta-85", "final-intercontinental-85"],
      camisetasUsadas: ["clasica-anos-80", "edicion-libertadores-85"],
    },
    {
      id: "redondo",
      nombre: "Fernando Carlos Redondo",
      apodo: "El Príncipe",
      iniciales: "FR",
      posicion: "Mediocampista central",
      periodo: "1985 — 1990",
      debutFecha: "1985",
      debutDetalle: "Debut profesional surgido de inferiores",
      partidos: null,
      goles: null,
      titulos: ["Copa Interamericana 1986"],
      bio: "Considerado uno de los volantes centrales más elegantes del fútbol mundial. Argentinos Juniors fue su primera casa: debutó en Primera y desplegó allí el toque, la pausa y la jerarquía que después lo llevarían al Tenerife, al Real Madrid (Champions 1998 y 2000) y al Milan. Su recorrido empezó en La Paternal.",
      cita: null,
      partidosDestacados: [],
      camisetasUsadas: ["clasica-anos-80"],
    },
    {
      id: "cambiasso",
      nombre: "Esteban Matías Cambiasso",
      apodo: "El Cuchu",
      iniciales: "EC",
      posicion: "Mediocampista central",
      periodo: "1995 — 1996",
      debutFecha: "1995",
      debutDetalle: "Debut profesional en Argentinos Juniors",
      partidos: null,
      goles: null,
      titulos: [
        "Champions League 2010 (Inter)",
        "Copa Mundial U-20 1997 (Selección Argentina)",
      ],
      bio: "El Cuchu dio sus primeros pasos en Primera con la camiseta de Argentinos antes de que River Plate lo comprara y lo proyectara al fútbol europeo. Carrera enorme en Real Madrid, Inter de Milán (donde fue parte del histórico triplete 2010 con Mourinho) y Leicester. Todo arrancó en La Paternal.",
      cita: null,
      partidosDestacados: [],
      camisetasUsadas: ["transicion-90"],
    },
    {
      id: "pavoni",
      nombre: "José Luis Pavoni",
      apodo: null,
      iniciales: "JP",
      posicion: "Defensor central",
      periodo: "1979 — 1986",
      debutFecha: null,
      debutDetalle: null,
      partidos: null,
      goles: null,
      titulos: [
        "Copa Libertadores 1985",
        "Campeonato Metropolitano 1984",
        "Campeonato Nacional 1985",
      ],
      bio: "Capitán y emblema del Argentinos campeón de América. Defensor sobrio, bandera del ciclo más glorioso del club. Levantó la Copa Libertadores 1985 frente a su gente.",
      cita: null,
      partidosDestacados: ["final-liberta-85"],
      camisetasUsadas: ["edicion-libertadores-85"],
    },
    {
      id: "ingunza",
      nombre: "Héctor Ingunza",
      apodo: null,
      iniciales: "HI",
      posicion: "Delantero",
      periodo: "1943 — 1946",
      debutFecha: "1943",
      debutDetalle: "Incorporación al primer equipo",
      partidos: null,
      goles: 137,
      titulos: [],
      bio: "El mayor goleador de la historia del club. Marcó 137 goles en partidos oficiales entre 1943 y 1946, en plena época de Segunda División tras el descenso. \"Difícilmente haya existido en la divisional otro jugador de un talento semejante\", recuerda la historia oficial del club: por verlo a él mucha gente se hizo hincha de Argentinos. Ídolo absoluto de una época difícil.",
      cita: null,
      partidosDestacados: [],
      camisetasUsadas: [],
    },
    {
      id: "pekerman",
      nombre: "José Néstor Pekerman",
      apodo: null,
      iniciales: "JP",
      posicion: "Volante",
      periodo: "Años 70",
      debutFecha: null,
      debutDetalle: "Conductor del equipo en los 70",
      partidos: null,
      goles: null,
      titulos: ["Campeón Mundial Juvenil 1995, 1997, 2001 (DT Selección Argentina)"],
      bio: "Volante de lujo de Argentinos en los años 70, destacado por su lectura del juego y conducción. Su carrera futbolística fue truncada por una lesión, pero su huella en el club fue enorme y luego se proyectaría como uno de los formadores más importantes del fútbol argentino: dirigió a las juveniles campeonas del mundo en 1995, 1997 y 2001 antes de hacerse cargo de la Selección mayor.",
      cita: null,
      partidosDestacados: [],
      camisetasUsadas: [],
    },
    {
      id: "vaccaro",
      nombre: "Luis Vaccaro",
      apodo: null,
      iniciales: "LV",
      posicion: "Delantero",
      periodo: "Años 20",
      debutFecha: null,
      debutDetalle: null,
      partidos: null,
      goles: null,
      titulos: [],
      bio: "La principal estrella de Argentinos en los años 20. En 1925, cuando Boca Juniors emprendió su legendaria gira por Europa —la primera de un equipo argentino—, le pidió a Argentinos a Vaccaro como refuerzo. Volvió cargado de gloria. Símbolo del primer Argentinos que jugó en Primera División.",
      cita: null,
      partidosDestacados: [],
      camisetasUsadas: [],
    },
    {
      id: "placeholder-1",
      nombre: "Próximo del archivo",
      apodo: null,
      iniciales: "··",
      posicion: "—",
      periodo: "—",
      placeholder: true,
      bio: "Esta ficha se completará al cargar la base de datos histórica del club. Cada jugador tendrá su biografía, estadísticas, partidos jugados y camisetas vestidas con relaciones cruzadas navegables.",
    },
  ],

  // ===== PARTIDOS =====
  partidos: [
    {
      id: "debut-maradona",
      titulo: "El debut de Maradona en Primera",
      fecha: "20 de octubre de 1976",
      anio: 1976,
      torneo: "Campeonato Metropolitano 1976",
      rival: "Talleres (Córdoba)",
      local: "Talleres",
      visitante: "Argentinos Juniors",
      resultado: "1 — 0",
      condicion: "visitante",
      desenlace: "derrota",
      cronica: "Diego Maradona ingresa al campo a los 16 minutos del segundo tiempo, con 15 años, 11 meses y 21 días. La derrota en el resultado importó poco: aquel partido fue el inicio de una de las carreras más grandes del fútbol mundial, y empezó con la camiseta del Bicho.",
      jugadoresClave: ["maradona"],
      camisetaUsada: "clasica-anos-80",
      destacado: true,
    },
    {
      id: "final-liberta-85",
      titulo: "Argentinos campeón de América",
      fecha: "Octubre de 1985",
      anio: 1985,
      torneo: "Final Copa Libertadores 1985",
      rival: "América de Cali",
      local: "Argentinos Juniors",
      visitante: "América de Cali",
      resultado: "5 — 4 (penales)",
      condicion: "neutral",
      desenlace: "victoria",
      cronica: "El club más de barrio que había levantado un trofeo continental. Tras la ida (1-0 en Buenos Aires) y la vuelta (1-0 para América en Cali), la final se definió en un tercer partido en Asunción que terminó 1-1 y se resolvió desde el punto del penal. Pavoni levantó la copa: Argentinos Juniors campeón de América.",
      jugadoresClave: ["batista", "borghi", "pavoni"],
      camisetaUsada: "edicion-libertadores-85",
      destacado: true,
    },
    {
      id: "final-intercontinental-85",
      titulo: "El Bicho frente al mundo",
      fecha: "8 de diciembre de 1985",
      anio: 1985,
      torneo: "Copa Intercontinental 1985",
      rival: "Juventus (Italia)",
      local: "Juventus",
      visitante: "Argentinos Juniors",
      resultado: "2 — 2 (4-2 penales)",
      condicion: "neutral",
      desenlace: "derrota",
      cronica: "Tokio. Argentinos Juniors le plantó cara a la Juventus de Michel Platini durante los 120 minutos. El partido terminó 2-2 y se definió por penales: la Juve ganó 4-2. Una derrota para los libros que dejó al club entre los más grandes del mundo aquel año.",
      jugadoresClave: ["batista", "borghi"],
      camisetaUsada: "edicion-libertadores-85",
      destacado: true,
    },
    {
      id: "interamericana-86",
      titulo: "Una vuelta olímpica más",
      fecha: "1986",
      anio: 1986,
      torneo: "Copa Interamericana 1986",
      rival: "Defence Force (Trinidad y Tobago)",
      local: null,
      visitante: null,
      resultado: "Campeón",
      condicion: "neutral",
      desenlace: "victoria",
      cronica: "Argentinos suma otro título internacional al palmarés ya glorioso del ciclo 1984–1986. La Copa Interamericana confirma que la consagración del año anterior no fue azar.",
      jugadoresClave: ["batista", "borghi", "redondo"],
      camisetaUsada: "edicion-libertadores-85",
      destacado: false,
    },
    {
      id: "metropolitano-84",
      titulo: "El primer título nacional",
      fecha: "1984",
      anio: 1984,
      torneo: "Campeonato Metropolitano 1984",
      rival: null,
      local: null,
      visitante: null,
      resultado: "Campeón",
      condicion: "neutral",
      desenlace: "victoria",
      cronica: "Argentinos Juniors gana su primer torneo nacional de Primera División. Es el inicio del ciclo más glorioso del club, que se completaría con la Libertadores y la Interamericana.",
      jugadoresClave: ["pavoni"],
      camisetaUsada: "clasica-anos-80",
      destacado: false,
    },
    {
      id: "placeholder-partido",
      titulo: "Próximo del archivo",
      fecha: "—",
      anio: null,
      torneo: "—",
      placeholder: true,
      cronica: "Este partido se completará al integrar la base histórica del club. Cada partido tendrá ficha, formaciones, goles minuto a minuto y camiseta utilizada.",
    },
  ],

  // ===== CAMISETAS =====
  camisetas: [
    {
      id: "clasica-anos-80",
      nombre: "Clásica de los años 80",
      anio: "1976 — 1985",
      descripcion: "La camiseta con la que Maradona debutó en Primera. Diseño tradicional con rayas verticales rojas y blancas, símbolo histórico del club.",
      patron: "rayas",
      partidosUsada: ["debut-maradona", "metropolitano-84"],
      jugadoresUsada: ["maradona", "batista", "borghi", "pavoni", "redondo"],
    },
    {
      id: "edicion-libertadores-85",
      nombre: "Edición Libertadores 1985",
      anio: "1985 — 1986",
      descripcion: "La casaca que vistió a los campeones de América. Pasó del barrio de La Paternal al estadio de Tokio enfrentando a la Juventus.",
      patron: "rayas",
      partidosUsada: ["final-liberta-85", "final-intercontinental-85", "interamericana-86"],
      jugadoresUsada: ["batista", "borghi", "pavoni"],
    },
    {
      id: "transicion-90",
      nombre: "Transición de los 90",
      anio: "1990 — 2000",
      descripcion: "Década de cambios en el club. La camiseta acompañó la formación de nuevas generaciones, entre ellas el debut de Esteban Cambiasso.",
      patron: "rayas-finas",
      partidosUsada: [],
      jugadoresUsada: ["cambiasso"],
    },
    {
      id: "moderna",
      nombre: "Era moderna",
      anio: "2000 — hoy",
      descripcion: "La camiseta actual continúa la herencia roja y blanca, ahora con tecnología deportiva y patrocinadores contemporáneos.",
      patron: "rayas",
      partidosUsada: [],
      jugadoresUsada: [],
    },
    {
      id: "placeholder-camiseta",
      nombre: "Próxima del archivo",
      anio: "—",
      placeholder: true,
      descripcion: "Esta camiseta se completará al integrar la base histórica del club, con foto real, descripción detallada y partidos en los que se vistió.",
      patron: "rayas",
    },
  ],

  // ===== HITOS / TIMELINE =====
  // Basado en la historia oficial del club por Hugo Frasso
  // (argentinosjuniors.com.ar/el-club/historia)
  hitos: [
    {
      anio: 1904,
      titulo: "Fundación del club",
      descripcion: "El 15 de agosto de 1904, en una obra en construcción en Araoz y Corrientes (Villa Crespo), un grupo de jóvenes con ideas socialistas funda el club. Inspirados en los Mártires de Chicago y el Día del Trabajador, lo bautizan Asociación Atlética y Futbolística Argentinos Unidos de Villa Crespo. Primer presidente, por unanimidad: Leandro Ravera Bianchi. Cuando se manda a hacer el sello, el fabricante sugiere acortar el nombre: nace «Asociación Atlética Argentinos Juniors».",
    },
    {
      anio: 1904,
      titulo: "Rojo y blanco por convicción",
      descripcion: "El club adopta como colores identificatorios el rojo con vivos blancos, en reemplazo del blanco y verde. Los rojos los eligen fieles a sus principios socialistas: ese año el Partido Socialista coloca su primer diputado en el Congreso, el Dr. Alfredo L. Palacios.",
    },
    {
      anio: 1905,
      titulo: "Primer partido oficial",
      descripcion: "Argentinos juega su primer partido en la Liga Central, contra el Club La Prensa. Pierde 12 a 1 — derrota catastrófica. Pero remontan en el torneo y terminan saliendo campeones de esa misma competencia.",
    },
    {
      anio: 1912,
      titulo: "El club de la lona",
      descripcion: "El club se instala en el predio de Fraga y Estomba: deja atrás la era del potrero. La cancha tenía una lona que cubría el alambrado para impedir la visual desde la calle, lo que les dio el apodo «El club de la lona». El canchero, además, criaba palomas mensajeras para enviar resultados cuando Argentinos jugaba de visitante.",
    },
    {
      anio: 1921,
      titulo: "Ascenso a Primera División",
      descripcion: "Tras ganar un torneo reducido entre los mejores del ascenso, Argentinos llega por primera vez a la Primera División. Ese mismo año, en la Vieja Cancha, derrota a Boca Juniors 3 a 1: un triunfo histórico.",
    },
    {
      anio: 1925,
      titulo: "Nuevo estadio en Av. San Martín",
      descripcion: "El 26 de julio de 1925 se inaugura el estadio de Av. San Martín y Punta Arenas, en un predio alquilado al Ferrocarril del Pacífico. Era moderno para la época: capacidad para más de 10.000 personas. Inauguración con triunfo 4-3 sobre Huracán en partido amistoso. Ese mismo año Boca Juniors se lleva prestado a Luis Vaccaro, la estrella del Bicho, en su gira histórica por Europa.",
      enlaces: { jugador: "vaccaro" },
    },
    {
      anio: 1926,
      titulo: "Subcampeón en Primera",
      descripcion: "Argentinos se consagra subcampeón. El club crece deportiva e institucionalmente.",
    },
    {
      anio: 1931,
      titulo: "Nace la Liga Profesional",
      descripcion: "Argentinos es uno de los 18 clubes que se desafilian de la Asociación Amateur Argentina para fundar la Liga Profesional. Lo más representativo del fútbol argentino, todo en una misma competencia.",
    },
    {
      anio: 1937,
      titulo: "Descenso y crisis",
      descripcion: "En plena crisis económica, Argentinos desciende junto a Quilmes. Es desalojado de su estadio por alquileres impagos: el Ferrocarril desmantela las estructuras. El club queda al borde de la desaparición.",
    },
    {
      anio: 1939,
      titulo: "Gastón García Miramón salva al club",
      descripcion: "Con apenas 100 socios, en una asamblea desesperada se nombra presidente a Gastón García Miramón —que ni siquiera era socio y estaba fuera del país. Aceptó el cargo y, de su propio bolsillo, alquiló el predio de Médanos y Boyacá, rescató los materiales embargados y empezó a construir un nuevo estadio. Salvó al club.",
    },
    {
      anio: 1940,
      titulo: "Estadio en Boyacá y Médanos",
      descripcion: "El 27 de abril de 1940 se inaugura el nuevo estadio con triunfo 2-1 sobre Barracas Central. Inicio de una campaña que terminaría con el club consagrándose campeón de Segunda División ese año. Equipo campeón: Pedroza, Zappa, Verrieres, Díaz, Lijo, Agosti, Turello, Capdeville, Dosseti, Leonardi y Pisapia.",
    },
    {
      anio: 1943,
      titulo: "Llega Héctor Ingunza",
      descripcion: "Se incorpora al primer equipo el mayor goleador de la historia del club. Entre 1943 y 1946 marca 137 goles en partidos oficiales. \"Difícilmente haya existido en la divisional otro jugador de un talento semejante\". Por verlo a él, mucha gente se hizo hincha de Argentinos.",
      enlaces: { jugador: "ingunza" },
    },
    {
      anio: 1955,
      titulo: "Campeones del ascenso",
      descripcion: "Después de 18 años en Segunda, Argentinos vuelve a Primera. Equipo campeón: Lus, Mascarello, Vidal, García, Distéfano, Pederzoli, Nappe, Carbone, López, Oscar Martín, Jorge Martín, Trigilli, Nakwaski, Panzutto, Sciarra y Tedeschi. La Paternal vive su fiesta.",
    },
    {
      anio: 1956,
      titulo: "Regreso a Primera División",
      descripcion: "Argentinos debuta en Primera en el viejo Gasómetro de San Lorenzo. Una conmovedora ovación recibió al equipo desde la tribuna colmada por miles de hinchas del Bicho. La línea media Distéfano-Pederzoli-Nappe se mantendría seis años y sería una de las más emblemáticas del fútbol argentino.",
    },
    {
      anio: 1960,
      titulo: "El equipo sensación",
      descripcion: "Con jugadores como Valentino, Ramacciotti, Malazzo, Canseco, Pando, Sciarra y Moreno, Argentinos forma un equipo recordado por su fútbol lujoso y contundente. Pierde el campeonato en las últimas fechas — quizás por «el mito de que un equipo chico no podía ser campeón» — pero entra en la leyenda del club.",
    },
    {
      anio: 1976,
      titulo: "Debut de Diego Maradona",
      descripcion: "El 20 de octubre de 1976, antes de cumplir los 16 años, Diego Armando Maradona debuta en Primera División ante Talleres de Córdoba. El técnico Juan Carlos Montes lo hace ingresar. Surgido de Los Cebollitas —el equipo juvenil dirigido por Francisco Cornejo— ya no abandonaría la Primera. Durante cuatro años lideraría la tabla de goleadores.",
      enlaces: { partido: "debut-maradona", jugador: "maradona" },
    },
    {
      anio: 1979,
      titulo: "Mundial Juvenil en Japón",
      descripcion: "Maradona, capitán, conduce a la Selección Argentina al título Mundial Juvenil 1979 en Japón. La historia oficial del club lo recuerda como «el mejor equipo de fútbol argentino que se viera jamás» en juveniles.",
      enlaces: { jugador: "maradona" },
    },
    {
      anio: 1980,
      titulo: "Subcampeón Metropolitano",
      descripcion: "De la mano de Maradona, Argentinos hace su mejor campaña en el profesionalismo hasta entonces y termina subcampeón del Metropolitano 1980.",
    },
    {
      anio: 1981,
      titulo: "Diego se va a préstamo a Boca",
      descripcion: "Maradona viste por última vez la camiseta del Bicho en el torneo de verano de Mar del Plata 1981. Es transferido a préstamo a Boca, al que conduce al campeonato ese año. Después sería transferido al Barcelona en una cifra récord: USD 5.800.000.",
      enlaces: { jugador: "maradona" },
    },
    {
      anio: 1984,
      titulo: "Campeón Metropolitano",
      descripcion: "Argentinos gana en forma brillante el Campeonato Metropolitano 1984: el primer título de Primera División de su historia.",
      enlaces: { partido: "metropolitano-84" },
    },
    {
      anio: 1985,
      titulo: "Campeón Nacional",
      descripcion: "Argentinos gana el Campeonato Nacional 1985. Segunda estrella en menos de un año: el ciclo glorioso está en marcha.",
    },
    {
      anio: 1985,
      titulo: "Campeón de América",
      descripcion: "Disputadísima final contra el América de Cali. Tras la ida (1-0 en Buenos Aires) y la vuelta (1-0 para América en Cali), la final se define en un tercer partido en Asunción: 1-1 y penales. Argentinos Juniors es campeón de la Copa Libertadores 1985.",
      enlaces: { partido: "final-liberta-85" },
    },
    {
      anio: 1985,
      titulo: "Final Intercontinental en Tokio",
      descripcion: "Argentinos enfrenta a la poderosa Juventus de Platini en Tokio. El 2-2 se recuerda como una de las mejores finales del torneo. Los penales fueron para la Juve. La historia oficial del club lo resume así: «hubo que conformarse con volver con las valijas llenas de fútbol».",
      enlaces: { partido: "final-intercontinental-85" },
    },
    {
      anio: 1986,
      titulo: "Copa Interamericana",
      descripcion: "Argentinos vence 1-0 a Defense Force de Trinidad y Tobago y se queda con la Copa Interamericana. Cierre de un ciclo glorioso 1984-1986.",
      enlaces: { partido: "interamericana-86" },
    },
    {
      anio: 1986,
      titulo: "Mundialistas en México",
      descripcion: "Sergio Batista y Claudio Borghi forman parte de la Selección Argentina campeona del mundo en México 86. Argentinos Juniors aporta dos jugadores al plantel campeón.",
      enlaces: { jugador: "batista" },
    },
    {
      anio: 1996,
      titulo: "Descenso después de 41 años",
      descripcion: "Tras la salida libre de Fernando Redondo y otros jugadores por un error administrativo, el club pierde una fortuna y empieza a declinar. Al final de la temporada 95-96, después de 41 años de militancia ininterrumpida en Primera, Argentinos sufre la amargura del descenso.",
      enlaces: { jugador: "redondo" },
    },
    {
      anio: 1997,
      titulo: "Retorno a Primera",
      descripcion: "Argentinos gana el campeonato del ascenso en la temporada 96-97. La noche del retorno, en la cancha de Deportivo Español, una multitud festeja el triunfo 1-0 sobre Gimnasia y Tiro.",
    },
    {
      anio: 2003,
      titulo: "Reinauguración del estadio",
      descripcion: "El 26 de diciembre de 2003, después de varios años haciendo de local en distintas canchas, el Bicho reinaugura su estadio en La Paternal. Una fecha que quedó en la memoria de todos.",
    },
    {
      anio: 2004,
      titulo: "Año del Centenario",
      descripcion: "Justo en el año de los 100 años del club, Argentinos vuelve a Primera tras una victoria resonante ante Talleres en Córdoba en la Promoción. Desde ese momento se mantendría ininterrumpidamente en la máxima categoría.",
    },
    {
      anio: 2008,
      titulo: "Semifinales de Copa Sudamericana",
      descripcion: "De la mano de Néstor Gorosito, Argentinos hace una resurrección notable: vuelve a las bases, solidifica el plantel y llega hasta las semifinales de la Copa Sudamericana 2008, a un paso de la gloria continental.",
    },
    {
      anio: 2010,
      titulo: "Campeón del Clausura",
      descripcion: "El retorno de Claudio Borghi, ídolo de la casa, transforma al equipo. Con un sprint final digno de un campeón, ganando en todos lados, Argentinos se consagra campeón del Torneo Clausura 2010 en la cancha de Huracán. La alegría volvió al barrio después de 25 años.",
      enlaces: { jugador: "borghi" },
    },
    {
      anio: 2011,
      titulo: "Vuelta a la Copa Libertadores",
      descripcion: "Como yapa del título, Argentinos regresa a la Copa Libertadores. La historia continúa.",
    },
    {
      anio: null,
      titulo: "Próximo hito del archivo",
      descripcion: "El equipo del museo seguirá sumando hitos a la línea de tiempo, con material fotográfico, video y testimonios del archivo histórico del club.",
      placeholder: true,
    },
  ],
};
