/* ============================================
   Museo Virtual AAAJ — Datos
   Esta versión usa datos públicos verificables (Wikipedia, sitio oficial)
   + placeholders donde se llenará con los Excels del archivo histórico.
   Cuando llegue la data real, reemplazar valores acá.
   ============================================ */

const DATA = {
  meta: {
    fundacion: "15 de agosto de 1904",
    estadio: "Diego Armando Maradona",
    barrio: "La Paternal, CABA",
    apodos: ["El Bicho", "Los Bichitos Colorados", "Los Cebollitas"],
    colores: ["#C8102E", "#FFFFFF"],
  },

  // ===== JUGADORES =====
  jugadores: [
    {
      id: "maradona",
      nombre: "Diego Armando Maradona",
      apodo: "El Diez",
      iniciales: "DM",
      posicion: "Mediocampista ofensivo",
      periodo: "1976 — 1981",
      debutFecha: "20 de octubre de 1976",
      debutDetalle: "Talleres (Córdoba) vs Argentinos Juniors",
      partidos: 167,
      goles: 116,
      titulos: ["Cebollitas — campeón juvenil"],
      bio: "Diego debutó en Primera con 15 años, 11 meses y 21 días — el más joven de la historia del club hasta ese momento. Surgido de Los Cebollitas, las inferiores que se hicieron leyenda en los 70, jugó cinco temporadas como bichito antes de partir a Boca. En Argentinos marcó 116 goles en 167 partidos, números que lo dejan entre los máximos goleadores históricos de la institución.",
      cita: {
        texto: "Cuando salí a la cancha por primera vez, sentí que el pasto me hablaba. Argentinos me hizo futbolista.",
        autor: "Diego Maradona",
      },
      partidosDestacados: ["debut-maradona", "final-liberta-85"],
      camisetasUsadas: ["clasica-anos-80"],
    },
    {
      id: "batista",
      nombre: "Sergio Daniel Batista",
      apodo: "El Checho",
      iniciales: "SB",
      posicion: "Mediocampista central",
      periodo: "1981 — 1988",
      debutFecha: "1981",
      debutDetalle: "Surgido de las inferiores del club",
      partidos: null,
      goles: null,
      titulos: [
        "Copa Libertadores 1985",
        "Copa Interamericana 1986",
        "Mundial México 1986 (Selección Argentina)",
      ],
      bio: "Volante central de marca y juego. Pieza clave del equipo de Argentinos campeón de América en 1985 y, un año después, mediocampista titular de la Selección Argentina campeona del mundo en México. Su trabajo silencioso en el medio fue uno de los pilares del ciclo más glorioso del club.",
      cita: {
        texto: "Aquel equipo del 85 fue una familia. Lo que conseguimos no se vuelve a repetir.",
        autor: "Sergio Batista",
      },
      partidosDestacados: ["final-liberta-85", "final-intercontinental-85"],
      camisetasUsadas: ["clasica-anos-80", "edicion-libertadores-85"],
    },
    {
      id: "borghi",
      nombre: "Claudio Daniel Borghi",
      apodo: "El Bichi",
      iniciales: "CB",
      posicion: "Mediocampista ofensivo",
      periodo: "1981 — 1987",
      debutFecha: "1981",
      debutDetalle: "Surgido de las inferiores del club",
      partidos: null,
      goles: null,
      titulos: [
        "Copa Libertadores 1985",
        "Copa Interamericana 1986",
        "Mundial México 1986 (Selección Argentina)",
      ],
      bio: "Enganche talentoso y una de las grandes figuras del Argentinos campeón de América. Tras la consagración en la Libertadores 1985, su nombre dio la vuelta al mundo cuando enfrentó a la Juventus de Platini en la final Intercontinental de Tokio. Mundialista en México 86 con la Selección.",
      cita: null,
      partidosDestacados: ["final-liberta-85", "final-intercontinental-85"],
      camisetasUsadas: ["clasica-anos-80", "edicion-libertadores-85"],
    },
    {
      id: "redondo",
      nombre: "Fernando Carlos Redondo",
      apodo: "El Príncipe",
      iniciales: "FR",
      posicion: "Mediocampista central",
      periodo: "1985 — 1990",
      debutFecha: "1985",
      debutDetalle: "Debut profesional surgido de inferiores",
      partidos: null,
      goles: null,
      titulos: ["Copa Interamericana 1986"],
      bio: "Considerado uno de los volantes centrales más elegantes del fútbol mundial. Argentinos Juniors fue su primera casa: debutó en Primera y desplegó allí el toque, la pausa y la jerarquía que después lo llevarían al Tenerife, al Real Madrid (Champions 1998 y 2000) y al Milan. Su recorrido empezó en La Paternal.",
      cita: null,
      partidosDestacados: [],
      camisetasUsadas: ["clasica-anos-80"],
    },
    {
      id: "cambiasso",
      nombre: "Esteban Matías Cambiasso",
      apodo: "El Cuchu",
      iniciales: "EC",
      posicion: "Mediocampista central",
      periodo: "1995 — 1996",
      debutFecha: "1995",
      debutDetalle: "Debut profesional en Argentinos Juniors",
      partidos: null,
      goles: null,
      titulos: [
        "Champions League 2010 (Inter)",
        "Copa Mundial U-20 1997 (Selección Argentina)",
      ],
      bio: "El Cuchu dio sus primeros pasos en Primera con la camiseta de Argentinos antes de que River Plate lo comprara y lo proyectara al fútbol europeo. Carrera enorme en Real Madrid, Inter de Milán (donde fue parte del histórico triplete 2010 con Mourinho) y Leicester. Todo arrancó en La Paternal.",
      cita: null,
      partidosDestacados: [],
      camisetasUsadas: ["transicion-90"],
    },
    {
      id: "pavoni",
      nombre: "José Luis Pavoni",
      apodo: null,
      iniciales: "JP",
      posicion: "Defensor central",
      periodo: "1979 — 1986",
      debutFecha: null,
      debutDetalle: null,
      partidos: null,
      goles: null,
      titulos: [
        "Copa Libertadores 1985",
        "Campeonato Metropolitano 1984",
        "Campeonato Nacional 1985",
      ],
      bio: "Capitán y emblema del Argentinos campeón de América. Defensor sobrio, bandera del ciclo más glorioso del club. Levantó la Copa Libertadores 1985 frente a su gente.",
      cita: null,
      partidosDestacados: ["final-liberta-85"],
      camisetasUsadas: ["edicion-libertadores-85"],
    },
    // Placeholders para llenar con el archivo histórico real
    {
      id: "placeholder-1",
      nombre: "Próximo del archivo",
      apodo: null,
      iniciales: "··",
      posicion: "—",
      periodo: "—",
      placeholder: true,
      bio: "Esta ficha se completará al cargar la base de datos histórica del club. Cada jugador tendrá su biografía, estadísticas, partidos jugados y camisetas vestidas con relaciones cruzadas navegables.",
    },
    {
      id: "placeholder-2",
      nombre: "Próximo del archivo",
      apodo: null,
      iniciales: "··",
      posicion: "—",
      periodo: "—",
      placeholder: true,
      bio: "Esta ficha se completará al cargar la base de datos histórica del club.",
    },
  ],

  // ===== PARTIDOS =====
  partidos: [
    {
      id: "debut-maradona",
      titulo: "El debut de Maradona en Primera",
      fecha: "20 de octubre de 1976",
      anio: 1976,
      torneo: "Campeonato Metropolitano 1976",
      rival: "Talleres (Córdoba)",
      local: "Talleres",
      visitante: "Argentinos Juniors",
      resultado: "1 — 0",
      condicion: "visitante",
      desenlace: "derrota",
      cronica: "Diego Maradona ingresa al campo a los 16 minutos del segundo tiempo, con 15 años, 11 meses y 21 días. La derrota en el resultado importó poco: aquel partido fue el inicio de una de las carreras más grandes del fútbol mundial, y empezó con la camiseta del Bicho.",
      jugadoresClave: ["maradona"],
      camisetaUsada: "clasica-anos-80",
      destacado: true,
    },
    {
      id: "final-liberta-85",
      titulo: "Argentinos campeón de América",
      fecha: "Octubre de 1985",
      anio: 1985,
      torneo: "Final Copa Libertadores 1985",
      rival: "América de Cali",
      local: "Argentinos Juniors",
      visitante: "América de Cali",
      resultado: "5 — 4 (penales)",
      condicion: "neutral",
      desenlace: "victoria",
      cronica: "El club más de barrio que había levantado un trofeo continental. Tras la ida (1-0 en Buenos Aires) y la vuelta (1-0 para América en Cali), la final se definió en un tercer partido en Asunción que terminó 1-1 y se resolvió desde el punto del penal. Pavoni levantó la copa: Argentinos Juniors campeón de América.",
      jugadoresClave: ["batista", "borghi", "pavoni"],
      camisetaUsada: "edicion-libertadores-85",
      destacado: true,
    },
    {
      id: "final-intercontinental-85",
      titulo: "El Bicho frente al mundo",
      fecha: "8 de diciembre de 1985",
      anio: 1985,
      torneo: "Copa Intercontinental 1985",
      rival: "Juventus (Italia)",
      local: "Juventus",
      visitante: "Argentinos Juniors",
      resultado: "2 — 2 (4-2 penales)",
      condicion: "neutral",
      desenlace: "derrota",
      cronica: "Tokio. Argentinos Juniors le plantó cara a la Juventus de Michel Platini durante los 120 minutos. El partido terminó 2-2 y se definió por penales: la Juve ganó 4-2. Una derrota para los libros que dejó al club entre los más grandes del mundo aquel año.",
      jugadoresClave: ["batista", "borghi"],
      camisetaUsada: "edicion-libertadores-85",
      destacado: true,
    },
    {
      id: "interamericana-86",
      titulo: "Una vuelta olímpica más",
      fecha: "1986",
      anio: 1986,
      torneo: "Copa Interamericana 1986",
      rival: "Defence Force (Trinidad y Tobago)",
      local: null,
      visitante: null,
      resultado: "Campeón",
      condicion: "neutral",
      desenlace: "victoria",
      cronica: "Argentinos suma otro título internacional al palmarés ya glorioso del ciclo 1984–1986. La Copa Interamericana confirma que la consagración del año anterior no fue azar.",
      jugadoresClave: ["batista", "borghi", "redondo"],
      camisetaUsada: "edicion-libertadores-85",
      destacado: false,
    },
    {
      id: "metropolitano-84",
      titulo: "El primer título nacional",
      fecha: "1984",
      anio: 1984,
      torneo: "Campeonato Metropolitano 1984",
      rival: null,
      local: null,
      visitante: null,
      resultado: "Campeón",
      condicion: "neutral",
      desenlace: "victoria",
      cronica: "Argentinos Juniors gana su primer torneo nacional de Primera División. Es el inicio del ciclo más glorioso del club, que se completaría con la Libertadores y la Interamericana.",
      jugadoresClave: ["pavoni"],
      camisetaUsada: "clasica-anos-80",
      destacado: false,
    },
    {
      id: "placeholder-partido",
      titulo: "Próximo del archivo",
      fecha: "—",
      anio: null,
      torneo: "—",
      placeholder: true,
      cronica: "Este partido se completará al integrar la base histórica del club. Cada partido tendrá ficha, formaciones, goles minuto a minuto y camiseta utilizada.",
    },
  ],

  // ===== CAMISETAS =====
  camisetas: [
    {
      id: "clasica-anos-80",
      nombre: "Clásica de los años 80",
      anio: "1976 — 1985",
      descripcion: "La camiseta con la que Maradona debutó en Primera. Diseño tradicional con rayas verticales rojas y blancas, símbolo histórico del club.",
      patron: "rayas",
      partidosUsada: ["debut-maradona", "metropolitano-84"],
      jugadoresUsada: ["maradona", "batista", "borghi", "pavoni", "redondo"],
    },
    {
      id: "edicion-libertadores-85",
      nombre: "Edición Libertadores 1985",
      anio: "1985 — 1986",
      descripcion: "La casaca que vistió a los campeones de América. Pasó del barrio de La Paternal al estadio de Tokio enfrentando a la Juventus.",
      patron: "rayas",
      partidosUsada: ["final-liberta-85", "final-intercontinental-85", "interamericana-86"],
      jugadoresUsada: ["batista", "borghi", "pavoni"],
    },
    {
      id: "transicion-90",
      nombre: "Transición de los 90",
      anio: "1990 — 2000",
      descripcion: "Década de cambios en el club. La camiseta acompañó la formación de nuevas generaciones, entre ellas el debut de Esteban Cambiasso.",
      patron: "rayas-finas",
      partidosUsada: [],
      jugadoresUsada: ["cambiasso"],
    },
    {
      id: "moderna",
      nombre: "Era moderna",
      anio: "2000 — hoy",
      descripcion: "La camiseta actual continúa la herencia roja y blanca, ahora con tecnología deportiva y patrocinadores contemporáneos.",
      patron: "rayas",
      partidosUsada: [],
      jugadoresUsada: [],
    },
    {
      id: "placeholder-camiseta",
      nombre: "Próxima del archivo",
      anio: "—",
      placeholder: true,
      descripcion: "Esta camiseta se completará al integrar la base histórica del club, con foto real, descripción detallada y partidos en los que se vistió.",
      patron: "rayas",
    },
  ],

  // ===== HITOS / TIMELINE =====
  hitos: [
    {
      anio: 1904,
      titulo: "Fundación del club",
      descripcion: "El 15 de agosto de 1904, un grupo de jóvenes anarquistas funda en el barrio de Villa Crespo el club que un siglo después se haría leyenda. Lo bautizan Argentinos Juniors.",
    },
    {
      anio: 1976,
      titulo: "Debut de Diego Maradona",
      descripcion: "Un pibe de 15 años, surgido de Los Cebollitas, ingresa por primera vez a una cancha de Primera. Argentinos Juniors le dio al mundo a Diego Maradona.",
      enlaces: { partido: "debut-maradona", jugador: "maradona" },
    },
    {
      anio: 1984,
      titulo: "Primer título nacional",
      descripcion: "Argentinos gana el Campeonato Metropolitano 1984, su primera estrella en Primera División.",
      enlaces: { partido: "metropolitano-84" },
    },
    {
      anio: 1985,
      titulo: "Campeón de América",
      descripcion: "El club levanta la Copa Libertadores frente al América de Cali en una final inolvidable, definida por penales en Asunción.",
      enlaces: { partido: "final-liberta-85" },
    },
    {
      anio: 1985,
      titulo: "Final Intercontinental en Tokio",
      descripcion: "Argentinos enfrenta a la Juventus de Platini por el título mundial de clubes. 2-2 y derrota por penales: una página dorada del fútbol argentino.",
      enlaces: { partido: "final-intercontinental-85" },
    },
    {
      anio: 1986,
      titulo: "Copa Interamericana",
      descripcion: "Otro trofeo internacional para el club. El ciclo glorioso 1984–1986 queda escrito en la historia del fútbol argentino.",
      enlaces: { partido: "interamericana-86" },
    },
    {
      anio: 1986,
      titulo: "Mundialistas en México",
      descripcion: "Sergio Batista y Claudio Borghi forman parte de la Selección Argentina que se consagra campeona del mundo. Argentinos Juniors aporta dos jugadores al plantel campeón.",
      enlaces: { jugador: "batista" },
    },
    {
      anio: 1996,
      titulo: "Estadio Diego Armando Maradona",
      descripcion: "El estadio del club es rebautizado en honor a Diego Maradona, en reconocimiento al jugador que dio al mundo desde sus inferiores.",
    },
    {
      anio: null,
      titulo: "Próximo hito del archivo",
      descripcion: "El equipo del museo seguirá sumando hitos del club a esta línea de tiempo, con material fotográfico y video del archivo histórico.",
      placeholder: true,
    },
  ],
};
